name: Angular Test

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install & Test Angular
        run: |
          cd ${{ inputs.working-directory }}
          npm ci
          npm run test -- --watch=false
