name: Docker Build and Push

on:
  workflow_call:
    inputs:
      image:
        description: 'Full image name (e.g., user/app)'
        required: true
        type: string
      context:
        description: 'Build context path'
        required: true
        type: string
      dockerfile:
        description: 'Path to Dockerfile'
        required: false
        default: 'Dockerfile'
        type: string
      push:
        description: 'Whether to push the image'
        required: false
        default: 'true'
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build \
            -t ${{ inputs.image }} \
            -f ${{ inputs.dockerfile }} \
            ${{ inputs.context }}

      - name: Push Docker image
        if: ${{ inputs.push == 'true' }}
        run: docker push ${{ inputs.image }}
